# Generated by Django 4.2.4 on 2023-09-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ko', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cardset')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cardcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=255)),
                ('word_ko', models.CharField(max_length=255)),
                ('association', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('variant', models.CharField(default='comprehension', max_length=255)),
                ('times_seen', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_wrong', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_time_correct', models.DateTimeField(blank=True, null=True)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cardset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cardcategory')),
            ],
        ),
    ]
