# Generated by Django 4.2.4 on 2023-09-07 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_time_correct',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 6, 23, 9, 5, 682267)),
            preserve_default=False,
        ),
    ]
