# Generated by Django 4.2.4 on 2023-09-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_card_last_time_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
